//! Is the failure capacity? ~100k parameters against ~2.5k informative labels is ~40
//! parameters per label, which is enough to memorise the training set outright. Sweep hidden
//! size with EVERYTHING ELSE FIXED -- same data, same epochs, same lr, same held-out set --
//! and read the held-out delta. One variable.
use nnue::Net;
use pipeline::datagen::{self, Rng, Sample};
use pipeline::trainer::Trainer;
use board::{Color, Position};

fn corr(net: &Net, data: &[Sample]) -> f64 {
    let mut s = Vec::new();
    let (mut xs, mut ys) = (Vec::new(), Vec::new());
    for d in data {
        if d.z == 0.0 { continue; }
        let p = match Position::from_fen(&d.fen) { Ok(p) => p, Err(_) => continue };
        xs.push(net.eval(&p, &mut s) as f64);
        ys.push(if p.stm == Color::White { d.z } else { -d.z } as f64);
    }
    let n = xs.len() as f64;
    if n < 10.0 { return 0.0; }
    let (mx, my) = (xs.iter().sum::<f64>() / n, ys.iter().sum::<f64>() / n);
    let (mut num, mut dx, mut dy) = (0.0, 0.0, 0.0);
    for i in 0..xs.len() {
        let (a, b) = (xs[i] - mx, ys[i] - my);
        num += a * b; dx += a * a; dy += b * b;
    }
    if dx <= 0.0 || dy <= 0.0 { return 0.0; }
    num / (dx.sqrt() * dy.sqrt())
}
fn z(r: f64) -> f64 { 0.5 * ((1.0 + r) / (1.0 - r)).ln() }

fn main() {
    let games: usize = std::env::args().nth(1).and_then(|s| s.parse().ok()).unwrap_or(400);
    // ONE data set, generated by ONE fixed net, shared by every arm.
    let gen_net = Net::random(128, 20260907);
    let mut rng = Rng(11);
    let mut train: Vec<Sample> = Vec::new();
    for _ in 0..games { datagen::play_game(&gen_net, 2, &mut rng, 6, 160, &mut train); }
    let mut held: Vec<Sample> = Vec::new();
    for _ in 0..(games / 3) { datagen::play_game(&gen_net, 2, &mut rng, 6, 160, &mut held); }
    let dec_he = held.iter().filter(|s| s.z != 0.0).count();
    let dec_tr = train.iter().filter(|s| s.z != 0.0).count();
    let se = (1.0f64 / (dec_he as f64 - 3.0)).sqrt();
    let ci = 1.96 * se * 2f64.sqrt();
    println!("  train {} pos ({dec_tr} decided)  held-out {} pos ({dec_he} decided)  interval +/-{ci:.3} (z)",
        train.len(), held.len());
    println!("  {:>7} {:>9} {:>10} {:>10} {:>10}", "hidden", "params", "before", "after", "delta-z");

    // MULTIPLE SEEDS PER ARM. A single before/after delta is dominated by regression to the
    // mean: the untrained correlation is pure initialisation noise (-0.28..+0.15 across seeds
    // here), so arms that happen to start low "improve" and arms that start high "decline".
    // Compare the AFTER distribution across arms instead, with the before distribution shown
    // so the reader can see the baseline is centred near zero.
    const SEEDS: usize = 6;
    let tr = Trainer::new(0.02, 0.0);
    println!("  {:>7} {:>9} {:>18} {:>18}", "hidden", "params", "before mean+/-sem", "after mean+/-sem");
    for h in [4usize, 16, 128] {
        let (mut b, mut a) = (Vec::new(), Vec::new());
        for s in 0..SEEDS {
            let mut net = Net::random(h, 1000 + s as u64 * 7919);
            b.push(corr(&net, &held));
            for e in 1..=6 { tr.epoch(&mut net, &train, 99 + e as u64); }
            a.push(corr(&net, &held));
        }
        let stat = |v: &Vec<f64>| {
            let n = v.len() as f64;
            let m = v.iter().sum::<f64>() / n;
            let sd = (v.iter().map(|x| (x - m) * (x - m)).sum::<f64>() / (n - 1.0)).sqrt();
            (m, sd / n.sqrt())
        };
        let (bm, bs) = stat(&b);
        let (am, asem) = stat(&a);
        let params = nnue::N_INPUTS * h + 2 * h + 1;
        let sig = (am - bm).abs() > 1.96 * (bs * bs + asem * asem).sqrt();
        println!("  {h:>7} {params:>9}   {bm:>+8.4}+/-{bs:.4}   {am:>+8.4}+/-{asem:.4}{}",
            if sig { "  *" } else { "" });
    }
    println!("\n  * = after differs from before beyond the combined sem, {SEEDS} seeds per arm");
    let _ = ci;
}
